### ISSUE TITLE
content about luna

### ISSUE THREAD

**Issue by flowerflow** [slavetrainermod/WT-Silver#104]
I have tried your game,and find  an interesting thing.
but，I don't know how to send the picture.
The question  was said that "could not find  the  label  Luna_reset "
I have try to fix that,but could not find where it(the label) is.
QAQ,How could i fix it?

**Comment by flowerflow** [comment]
![pic](https://user-images.githubusercontent.com/28246959/48671018-e8cbf780-eb5c-11e8-9576-c446387aec22.jpg)

**Comment by sniggie** [comment]
Lurker here. You can find the new label here: /__Renpy__/_luna_/_luna_.rpy as **reset_luna**

Pretty sure, they changed the label name and forgot to update that file.

Hope this helps at all.

**Comment by flowerflow** [comment]
Thanks，I have fix it。
（I am sorry because i still don't have a paypal card。when i got one,i will go to  your patron.com Url and support you  : ）  )
