### ISSUE TITLE
Unable to unlock additional public requests

### ISSUE THREAD

**Issue by Otsdarva68** [slavetrainermod/WT-Silver#121]
Using v1.34b on Windows 10. I am unable to unlock public requests, neither normally nor via the cheat (Cheat says "public requests unlocked") but they are still "a vague idea" in the menu. This affects Luna content and public ending.

**Comment by ThatGuy115** [comment]
Have you read the fiction books or used the cheat to increase Imagination? Because the "a vague idea" bit usually means your "Imagination" stat is too low.

**Comment by Otsdarva68** [comment]
I had read all fiction books. After using the "max imagination" cheat, I can see them and use them. Thanks! I'll close this issue now
