### ISSUE TITLE
Feedback on new changes & some requests

### ISSUE THREAD

**Issue by just2toss** [slavetrainermod/WT-Silver#122]
I love a lot of things about the 1.34 update; however, there's some things that I would like tweaked/reverted that I think would give a better user experience:

- I appreciate being able to see the stats for the various characters; however, I was wondering if it's possible to keep track of which character you last viewed the stats for, and show them when opening the stats screen (as opposed to always showing the Geni).

- I really like all the new stats, great work! Any chance you could show Hermione's mood as a stat, rather than just a facial expression?

- IMO the original map was much easier to decipher than the map that's used in 1.34. It took me a while to figure out where the Weasley's shop is, and the clothing store. Map2 has some very attractive features - namely things are spelled out instead of symbols (though as a novice I'd have no idea what Mal is, and it's not labeled as a store - changing it to Mal's store would be a welcomed improvement) .

- I really like having a graphical selection when clicking on the door to determine which character to summon. An improvement, would be when using the keyboard to choose a character to summon, having more contrast for the selected entry would be appreciated. 

All in all, great new features. Thanks so much for all your work.

**Comment by Mad-Merlin** [comment]
- Good suggestion. Was what I intended originally. Need sure why it defaults to Genie now.
- Will add her mood to the stats screen.
- There might be a tutorial for the map in one of the next updates to make the symbols more clear.
- What do you mean by contrast? A richer hover color?

**Comment by Mad-Merlin** [comment]
Added your first 2 suggestions.

**Comment by just2toss** [comment]
Thanks! Yes a richer hover color.
