### ISSUE TITLE
Bug in stories in the mirror of Erised that causes the game to crash

### ISSUE THREAD

**Issue by jahall99** [slavetrainermod/WT-Silver#124]
In v1.34b, in both parts of the "A bad time to disrobe" story in the mirror of Erised, the game crashes because it wants a file top_1.png that doesn't exist. Files that do exist are top_1g.png and top_1s.png, so a work-around is to copy one of those files to top_1.png

**Comment by Mad-Merlin** [comment]
Fixed in next update.
