### ISSUE TITLE
Final Event for LetsHaveSex can never occur

### ISSUE THREAD

**Issue by CatgirlsRLove** [slavetrainermod/WT-Silver#19]
There are four events in that sequence; due to how the if statements are coded the fourth event can never occur because the third if statement will always be true after a certain point. Said if statement is: 
`elif hg_pf_LetsHaveSex_OBJ.points >= 2:`
So as long as OBJ.points is greater than or equal to 2, that block will be executed. That means the if statement for the fourth and final event, where Luna walks in: 
`elif hg_pf_LetsHaveSex_OBJ.points >= 3:`
Just can't happen, because the prior elseif will always be true at that point. 

So, unless the idea is for the final Luna event to be the one repeated endlessly (or the event just isn't ready to be seen), the elseif controlling the third time event should probably be changed to something like:
`elif hg_pf_LetsHaveSex_OBJ.points >= 2 and hg_pf_LetsHaveSex_OBJ.points != 3: `
So that the final event will occur only once before the third event is repeated indefinitely. 

Also should probably add code to the end of the fourth event so that Luna doesn't just stand there forever after the event ends. Not familiar with the code yet but "call luna_away" seemed to work.

**Comment by asease1** [comment]
i think that it was the old way to unlock luna

**Comment by asease1** [comment]
This will be added to the mirror in some update
