### ISSUE TITLE
Permission required?

### ISSUE THREAD

**Issue by Vreejack** [slavetrainermod/WT-Silver#65]
brand spanking new at this collaborative stuff, but I think I was proceeding correctly. I created a new branch ("chit-chat-refinements") but I was unable to pull it. It looks like I need permission. Makes sense.

Can I help out?

**Comment by asease1** [comment]
You can fork the project make the changes ind you project and then make a pull requist. Then one of the admin will check the changes and then merge it

**Comment by Vreejack** [comment]
Thanks. Done.
