### ISSUE TITLE
Suggestion: Making Hermione actually sound English

### ISSUE THREAD

**Issue by Vreejack** [slavetrainermod/WT-Silver#67]
As someone who spent a lot of time in England while growing up, it is astonishingly clear to me that--based on the way she talks--our Hermione is not actually English at all, but American. I don't think this is a serious issue, and it would require quite a bit of work to correct and even maintain, but I wanted to get it off my chest so that I can move on.

If we want to, I can start massaging the text, but there are a few things to consider first.
1. It will require touching a lot of files. This is "her" game, after all. It's a bit of a step away from what Akabur did.
2. If we assume that Genie speaks like an American, then there is a lot of room for comedic confusion, some of which I have experienced myself.
3. It will require some maintenance for the duration of the game, so it would be best to make sure the "maintainer" is actually fully invested in the project and willing to stick it out, by which I mean that this will have to be brought up again some time in the future before anything is done.

**Comment by asease1** [comment]
most of the game is written in UK English there is just not used slang from UK and more common words to make it easy for everyone to understand
