### ISSUE TITLE
m "Prostitutes are getting paid to have sex with men..."

### ISSUE THREAD

**Issue by wasya2009** [slavetrainermod/WT-Silver#77]
https://github.com/slavetrainermod/WT-Silver/blob/32d7e5d1b57e89e04e021e81b4639dcd0ca55abc/game/__Renpy__/_hermione_/personal_favours/hg_pf_08_LetMeTouchThem.rpy#L124

**Comment by Vreejack** [comment]
Agree.
Should be "Prostitutes are paid to have sex with men."
I noticed it during first playthrough.
