### ISSUE TITLE
Outer line on skirt 7 needs to be wider to hide panties

### ISSUE THREAD

**Issue by Vreejack** [slavetrainermod/WT-Silver#78]
a couple of panties stick out farther than new skirt 7 and need to be covered

**Comment by Vreejack** [comment]
Also, there is no "lift skirt" graphic.

**Comment by Mad-Merlin** [comment]
There is no lift skirt variant because the skirt already shows everything there is to show.
I will see what I can do for the skirt width but it's not a high priority right now.
